### ISSUE TITLE
Conflicting migrations

### ISSUE THREAD

**Issue by bobperik** [vicktornl/django-secret-sharing#11]
Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_alter_secret_created_at, 0002_auto_20220525_1008 in django_secret_sharing).

Both migrations have a dependency to `0001_add_secret_model`

**Comment by robmoorman** [comment]
Looking at https://github.com/vicktornl/django-secret-sharing/tree/master/src/django_secret_sharing/migrations
I dont see the `0002_alter_secret_created_at` file?
